#!/bin/bash

gi() { cd "$GIT_X_BASE/$1"; }

# Bash completion for gi

# http://unix.stackexchange.com/questions/28283/autocomplete-of-filename-in-directory
_giComplete()
{
  local cur=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=( $(compgen -W "$(ls -A "$GIT_X_BASE")" -- $cur) )
}

complete -F _giComplete gi
